### PR TITLE
Browser is transpiled. Module is not.

### PR DESCRIPTION
**Pull request by indexzero**

### CODE REVIEW

**Review by dusave — APPROVED** [review]
Should we add a `CHANGELOG` entry for this?

**Review by chrisvogt — APPROVED** [review]
LGTM

**Review by JacopoDaeli — APPROVED** [review]
LGTM 💯

**Review by rxmarbles — APPROVED** [review]

**Review by mayank23 — APPROVED** [review]

**Comment by rxmarbles** [comment]
@indexzero I believe this PR can be closed due to #7 being merged

**Comment by 3rd-Eden** [comment]
Agreed.

**Pull request closed without merging**
